server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  wal:
    dir: /loki/wal

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

chunk_store_config:
  max_look_back_period: 0s

limits_config:
  enforce_metric_name: false
