global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "prod-servers"
    ec2_sd_configs:
      - port: "9100"
        filters:
          - name: "tsg:Environment"
            values: ["prod"]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
      - source_labels: [__meta_ec2_instance_id]
        target_label: __instance__
